<a href="https://colab.research.google.com/github/wajdi404/NumPy-Exercises-Solutions/blob/main/Create_NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.21.6'

**There are 6 general mechanisms for creating Numpy arrays:**

1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)


### **1. From Python structures to NumPy Arrays**


---



In [ ]:
Arr_1D = np.array( [1, 2, 3, 4] )
print( Arr_1D.dtype )
print( Arr_1D.shape )
print( Arr_1D )

int64
(4,)
[1 2 3 4]


In [ ]:
Arr_2D = np.array( [[1, 2], [3.0, 4]], )
print( Arr_2D.dtype )
print( Arr_2D.shape )
print( Arr_2D )

float64
(2, 2)
[[1. 2.]
 [3. 4.]]


In [ ]:
Arr_3D = np.array( [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=np.int8 )
print( Arr_3D.dtype )
print( Arr_3D.shape )
print( Arr_3D )

int8
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
Arr_1D = np.array( [1, 2, 3, 4], dtype=complex)
print( Arr_1D.dtype )
print( Arr_1D.shape )
print( Arr_1D )

complex128
(4,)
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
# When you use numpy.array to define a new array, you should consider 
# the dtype of the elements in the array, which can be specified explicitly.
# If you are not careful with dtype assignments, you can get unwanted overflow, as such

a = np.array( [127, 128, 129], dtype=np.int8) # An 8-bit signed integer represents integers from -128 to 127
print(a.shape)
print(a.dtype)
print(a)

(3,)
int8
[ 127 -128 -127]


In [ ]:
a = np.array( ( 2, 3, 4), dtype=np.uint8)
b = np.array( ( 5, 6, 7), dtype=np.uint8)
c = a - b.astype(np.int8)
print(c.shape)
print(c.dtype)
print(c)

(3,)
int16
[-3 -3 -3]


### **2. Intrinsic NumPy array creation functions**


---


<p align="justify">
NumPy has over 40 built-in functions for creating arrays. These functions can be split into roughly three categories, based on the dimension of the array they create:
<p>

#### **Buit-in Function for Creating 1D Arrays**

In [ ]:
# linspace( start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
a = np.linspace( start=0, stop=10, num=10, endpoint=False)
print(a.dtype)
print(a.shape)
print(a)

float64
(10,)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
b = np.linspace( start=0, stop=10, num=10, retstep=True, dtype=np.int64)
print(b[0].dtype)
print(b)

int64
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]), 1.1111111111111112)


In [ ]:
# np.arange( [start, ] stop, [step, ] dtype=None, *, like=None)
# Similar to linspace, but uses a step size (instead of the number of samples).
a = np.arange( stop=10)
print(a.dtype)
print(a)

int64
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b = np.arange( start=2, stop=10, dtype=float)
print(b)
print(b.dtype)

[2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [ ]:
c = np.arange( start=2, stop=3, step=0.1)
print(c.dtype)
print(c.shape) # Length of result is ceil((stop - start)/step)
print(c)

float64
(10,)
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [ ]:
# geomspace( start, stop, num=50, endpoint=True, dtype=None, axis=0)
# Similar to linspace, but with numbers spaced evenly on a log scale (a geometric progression).
a = np.around(np.geomspace( start=1, stop=1024, num=11)).astype("int64")
print(a.dtype)
print(a)

int64
[   1    2    4    8   16   32   64  128  256  512 1024]


In [ ]:
# logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# Return numbers spaced evenly on a log scale.
a = np.logspace( start=1, stop=10, num=10, base=2)
print(a.dtype)
print(a)

float64
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


#### **Buit-in Function for Creating 2D Arrays**

In [ ]:
# np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
# Return a 2-D array with ones on the diagonal and zeros elsewhere.


In [ ]:
# np.identity(n, dtype=None, *, like=None)
# Return the identity array, which is a square array with ones on main diagonal.



In [ ]:
# np.diag( v, k=0)
# Extract a diagonal or construct a diagonal array.

a = np.array( [ [0, 1, 2], [3, 4, 5], [6, 7, 8] ] )
print(np.diag(a, k=0))
print(np.diag(a, k=1))
print(np.diag(a, k=-1))
print(np.diag( np.diag(a) ))

In [ ]:
#  np.diagflat( v, k=0)
# Create a two-dimensional array with the flattened input as a diagonal.
print( np.diagflat( [ [1,2], [3,4] ], k=0 ) )
print( np.diagflat( [ 1, 2], k=-1 ) )

In [ ]:
#  np.tri( N, M=None, k=0, dtype=<class 'float'>, *, like=None)
# Return an array with ones at and below the given diagonal and zeros elsewhere.
print( np.tri( N=3, M=5, k=2, dtype=int) )
print( np.tri( N)3, M=5, k=-1) )

In [ ]:
#  np.tril( m, k=0)
# Return the lower triangle of an array m
print(np.tril( m=[[1,2,3], [4,5,6], [7,8,9], [10,11,12] ])) 

In [ ]:
# np.triu( m, k=0)
# Return the upper triangle of an array m
print(np.triu( m=[[1,2,3], [4,5,6], [7,8,9], [10,11,12] ]))

In [ ]:
# np.vander( x, N=None, increasing=False)
# Generate a Vandermonde matrix.
x = np.array([1, 2, 3, 5])
print(np.vander( x, N=3))

#### **Buit-in Function for Creating nD Arrays**

In [ ]:
np.ones()

In [ ]:
np.empty()

In [ ]:
np.arange()

In [ ]:
np.linspace()

### **3. Replicating, joining, or mutating existing arrays**


---


<p align="justify">

<p>