<a href="https://colab.research.google.com/github/wajdi404/NumPy-Exercises-Solutions/blob/main/Create_NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.6'

**There are 6 general mechanisms for creating Numpy arrays:**

1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)


### 1. From Python structures to NumPy Arrays 

In [15]:
Arr_1D = np.array( [1, 2, 3, 4] )
print( Arr_1D.dtype )
print( Arr_1D.shape )
print( Arr_1D )

int64
(4,)
[1 2 3 4]


In [16]:
Arr_2D = np.array( [[1, 2], [3.0, 4]], )
print( Arr_2D.dtype )
print( Arr_2D.shape )
print( Arr_2D )

float64
(2, 2)
[[1. 2.]
 [3. 4.]]


In [17]:
Arr_3D = np.array( [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=np.int8 )
print( Arr_3D.dtype )
print( Arr_3D.shape )
print( Arr_3D )

int8
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
Arr_1D = np.array( [1, 2, 3, 4], dtype=complex)
print( Arr_1D.dtype )
print( Arr_1D.shape )
print( Arr_1D )

complex128
(4,)
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [41]:
# When you use numpy.array to define a new array, you should consider 
# the dtype of the elements in the array, which can be specified explicitly.
# If you are not careful with dtype assignments, you can get unwanted overflow, as such

a = np.array([127, 128, 129], dtype=np.int8) # An 8-bit signed integer represents integers from -128 to 127
print(a.shape)
print(a.dtype)
print(a)

(3,)
int8
[ 127 -128 -127]


In [42]:
a = np.array([ 2, 3, 4], dtype=np.uint8)
b = np.array([ 5, 6, 7], dtype=np.uint8)
c = a - b.astype(np.int8)
print(c.shape)
print(c.dtype)
print(c)

(3,)
int16
[-3 -3 -3]


### 2. Intrinsic NumPy array creation functions
<p align="justify">
NumPy has over 40 built-in functions for creating arrays. These functions can be split into roughly three categories, based on the dimension of the array they create:
<p>


*   1D Arrays => e.g. np.linspace and np.arange
*   2D Arrays => e.g. np.eye, np.diag, and np.vander
*   nD Arrays =>  e.g. np.ones, np.zeros, and np.random


In [46]:
# 1D Arrays
# np.arange creates arrays with regularly incrementing values.
# np.arange( [start, ] stop, [step, ] dtype=None, *, like=None)
a = np.arange( 10)
print(a)
b = np.arange( 2, 10, dtype=float)
print(b)
c = np.arange( 2, 3, 0.1)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [ ]:
# linspace( start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


In [ ]:
np.ones()

In [ ]:
np.empty()

In [ ]:
np.arange()

In [ ]:
np.linspace()